### ISSUE TITLE
Submit and scatter to all workers

### ISSUE THREAD

**Issue by mrocklin** [blaze/distributed#110]
Sometimes we need to send a piece of data or to perform a computation on all workers.  This might be for a critical piece of data like a database connection that we don't want to have to bounce between the workers at random.

From an API perspective the functions `submit` and `scatter` could take an `all=True` or `broadcast=True` keyword argument, which would immediately trigger a computation on all workers, or on all workers listed within the `workers=` keyword.

From an implementation perspective this operation is a bit odd.  We can't rely on the typical scheduling mechanics to handle it because they'll try to be too efficient.  My guess is that we will jump the queue and and will send the task to each current worker immediately.  I don't intend to support new workers that come in after the submit call.  

If we wanted to roll operations like this generally into the scheduler then we could add the concept of `num_replications` to tasks to enable us to ask that a certain task run on a certain number of independent workers.  For broadcast we would set this to `inf`.  This is a bit too much machinery for me right now, but might be a good generalization if this idea becomes more useful later.

In either case I intend to return a single future with the same key.  That future will probably have a `finished` status after just the first worker finishes the task, which may cause some issues.

cc @danielfrg @broxtronix

**Comment by mrocklin** [comment]
Added a `broadcast=` keyword argument to scatter.  Closing.

**Comment by rainwoodman** [comment]
What about reducing data cross workers?

Currently we can use `as_completed` on the client to reduce results one by one, but it seems like a tree based worker aware algorithm can make better use of the bandwidth.

**Comment by mrocklin** [comment]
Yeah, you could do this today.   Many of our examples (like the standard delayed and futures examples in dask-examples) show how to do this.  Also all of dask.array and dask.dataframe do this automatically in their reductions.

If you are proposing doing future work then I recommend raising a new issue.

**Comment by rainwoodman** [comment]
I never thought it can be done this way -- with such simple implementation
I agree there is no need to add a new API.

(link to the future example:
https://github.com/dask/dask-examples/blob/8625d06233e9ac584ff623999d5b6488969e6826/delayed.ipynb
)
