### ISSUE TITLE
Nanny process

### ISSUE THREAD

**Issue by mrocklin** [blaze/distributed#22]
Currently we spin up `dworker` processes on remote nodes.  These workers run our computations directly.  It might be preferable to instead launch a super or "nanny" process that launches `dworker`.

### This has the following advantages:

*  Makes the network robust to catastrophic worker failure, such as would be caused by a segfault.  Nanny can just restart the worker
*  Can cleanly restart the worker nodes on user request, such as when they accidentally send up a very long running function
*  Can consistently monitor and send heartbeats to the scheduler.

### This also raises some questions

*  How should the scheduler interact with the nanny?  Does the nanny proxy all communications to the worker (if so is there a significant cost/overhad here?)  Does the scheduler have two connections open?

**Comment by mrocklin** [comment]
I wanted to see how much overhead proxying all communications through a nanny process would be.  Here is a tiny benchmark.

```python
In [1]: from multiprocessing import Process, Queue

In [2]: def f(inp, out):
    while True:
        data = inp.get()
        out.put(data)
   ...:         

In [3]: inp, out = Queue(), Queue()

In [4]: proc = Process(target=f, args=(inp, out))

In [5]: proc.start()

In [6]: %time for i in range(1000): inp.put(1); out.get()
CPU times: user 135 ms, sys: 49 ms, total: 184 ms
Wall time: 279 ms

In [7]: import numpy as np

In [8]: x = np.empty(1000000, 'f8')  # 8MB

In [9]: %time for i in range(1000): inp.put(x); out.get()
CPU times: user 13.1 s, sys: 17.4 s, total: 30.5 s
Wall time: 56.6 s

In [10]: 8e6 * 1e3 / 56 / 1e6  # MB/s
Out[10]: 142.85714285714286
```

So pushing our data through a nanny process in this manner adds an extra 150MB/s of (bidirectional) bandwidth resistance (on an old and low-powered laptop.)  This matches the general intuition of IPC maxing out at 300MB/s.  There are alternatives here, like communicating directly with the sub-process or finding a way to share memory.  I'm not sure how big of a deal this is.

@minrk, I believe that you've thought about this topic before.  Do you have thoughts on how to do this better?

**Comment by mrocklin** [comment]
After thinking about this a bit more it seems useful for the worker to maintain its own connections, particularly because proxying all of the peer-to-peer connections might become unruly.  

So presumably the scheduler will maintain a control connection to the nanny process, separate to the data connection to the worker.

**Comment by minrk** [comment]
It looks like you have come to the same conclusion I did in my thinking about a KernelNanny for IPython - that the Nanny should only sit on the control channel, and execution should go direct to the actual worker. That way the nanny system cannot interfere with execution when everything is going smoothly, only when you actually want to intervene.

**Comment by mrocklin** [comment]
We now have a nanny process.  It doesn't do much except for kill and restart the workers, but its there and could do more in the future if we desire.  Closing.
