### ISSUE TITLE
Distribute .py files or eggs

### ISSUE THREAD

**Issue by mrocklin** [blaze/distributed#23]
Users are likely to have custom code that they want to ship out to all of the worker nodes and then load up into the running worker process.  What is the right way to accomplish this?

To be clear, there are probably two technical challenges:

1.  Distribute files between nodes
2.  Inject those files into the environment of the running worker, possibly reloading over existing modules (I believe that Python has mechanisms for this.)

We could punt this off to other tools, but it's probably pretty useful to have directly within distributed or on closely attached tools.  Ideally we can do this in such a way that it does not become a significant maintenance burden.

I wonder if @quasiben , @danielfrg , or @martindurant have thoughts on how best to do this.

**Comment by danielfrg** [comment]
[Fabric](https://github.com/fabric/fabric) is the first thing that comes to my mind.

People can write simple fabric files that upload the `.py` files to multiple nodes with very few lines of code and they just use using the `fab` command.

If you want to build a helper tools then I am not a fan of fabric in that case, I have been playing with other smaller libraries like [parallel-ssh](https://github.com/pkittenis/parallel-ssh) here: https://github.com/danielfrg/remote-pip and i like it more than fabric for custom stuff.

**Comment by mrocklin** [comment]
An alternative is that I just use the `distributed` network itself to move bytes around.

**Comment by martindurant** [comment]
Am I right in remembering that fabric is the main dependency holding anaconda-cluster to py27? When you execute acluster put (i.e., send files to nodes from outside the cluster), it must be fabric that does that. Any tool that has to set up SSH connections will be slow compared to an already-open TCP connection, but that may not be a problem for a rare operation.

About reloading modules, ipython's autoreload only work in an interactive shell, but there is http://ipython.org/ipython-doc/dev/api/generated/IPython.lib.deepreload.html; and tornado's autoreload (http://tornadokevinlee.readthedocs.org/en/latest/autoreload.html) is rather specialised in intent and needs an event loop - it might be coerced to do the job, though.
Would it be correct to say that watching for new modules only happens while a worker is idle and/or explicitly when files are sent? If only the latter, then it may be enough to look for a match in the set of files currently imported:
`[getattr(m, '__file__', None) for m in sys.modules.values()]`

On a side issue, it may be a good idea to be able to "reset" worker processes to clear imported modules and data; or perhaps even to explicitly restart worker processes from scratch.

**Comment by mrocklin** [comment]
The autoreload technology probably uses something like `importlib` under the hood.

https://docs.python.org/3/reference/import.html

**Comment by martindurant** [comment]
There was a demo Friday talk describing funny things that can be done with the import machinery, but changing import specs doesn't prevent the initial check for a cached module.

To change that, one might replace the `__import__()` function. Might be interesting to experiment with this.

**Comment by martindurant** [comment]
This little piece of code shows that overwriting `__import__` is flaky, perhaps there's a way, but probably best not touch.
```
import builtins
old_imp = builtins.__import__

def newimp(*args):
    print(args[0])
    old_imp(*args)

builtins.__import__ = newimp
    
import sys
import os
import numpy as np
```
(the first two work, numpy does not, either because it imports __future__, which is special, or because an import within a package is somehow different)

I recommend having workers receive files directly, and _if_ it is a python file and _if_ it is references in sys.modules, to delete that reference upon receipt. That won't guard against code changes in-place. Also a `reset` method would be very useful when developing or between independent jobs.

Alternatively, the ipython reload looks like it can be readily adapted to be called directly: at call time it checks all modules for change and reloads those that need it (with the added bonus of updating function/class code in place).

**Comment by quasiben** [comment]
It might be worth taking a glance at (streamparse)[https://streamparse.readthedocs.org/en/master/quickstart.html#project-structure) and note how they optionally ship a pip requirements.txt file to be installed in a virtualenv as part of a job.  @danielfrg would be more knowledgable here

**Comment by mrocklin** [comment]
I think that a good first step to this is to send .py and .eggs using distributed and ignore reloading for now (which apparently requires fancy magic.)

Where is the right place to put .py and .egg files.  Just dump into the local directory where the worker is running?  I definitely don't want to get into the environment management game.

Or in other words, is there anything wrong with the following naive approach:

1.  Load file from local disk as bytes.  Send file and filename to worker nodes.
2.  Save file as filename in worker nodes' local directories
3.  Ensure that `'.' in sys.path` for the workers

Sending a requirements.txt or environment.yaml file to the workers sounds like a nice idea.  I'll need to implement some sort of nanny process before this becomes feasible.  (the thing managing the environment *is* the Python process that's about to do this work, so it can't update too much of itself.)

**Comment by danielfrg** [comment]
Fabric is indeed what keeps Anaconda Cluster in Python 2. I do not recommend to make fabric a dependency of any project but its nice to tell people an easy solution that you they can just install and you dont have to write any code.

Streamparse does create virtualenvs for every project they deploy to storm.

I agree thats a good enough just to use distributed maybe you can just use cloudpickle serialize to send the libraries?

The naive aproach Matt describes sounds good to me maybe put them in a temporal directory? https://docs.python.org/2/library/tempfile.html I do stuff like that using py.test but those files are removed when the test ends.

**Comment by mrocklin** [comment]
OK, some work has happened (and is happening) here.

In https://github.com/blaze/distributed/pull/28 (merged) we add the ability to upload files to a temporary directory that is placed on `sys.path`.

In https://github.com/blaze/distributed/pull/35 (not yet merged) we automatically reload files using stdlib `reload` functionality, but not any sort of deep reloading.

https://github.com/blaze/distributed/pull/35 could use a bit of feedback if anyone has the time.

**Comment by broxtronix** [comment]
Hey @mrocklin!   I took the new .egg uploading code out for a spin this morning (updated to the latest master branch), but I'm afraid it still does not work on my cluster.  It seems to hang when I run 
```
executor.upload_file("~/fringe/dist/fringe-0.7a0-py3.4.egg")
```
If I interrupt execution of this line of code, the iPython traceback seems to indicate that the code is stuck waiting to acquire a semaphore:
```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-17-5e5ceac23586> in <module>()
----> 1 executor.upload_file("~/fringe/dist/fringe-0.7a0-py3.4.egg")

/home/ec2-user/anaconda3/lib/python3.4/site-packages/distributed-1.6.0-py3.4.egg/distributed/executor.py in upload_file(self, filename)
    758         """
    759         result = sync(self.loop, self._upload_file, filename,
--> 760                         raise_on_error=False)
    761         if isinstance(result, Exception):
    762             raise result

/home/ec2-user/anaconda3/lib/python3.4/site-packages/distributed-1.6.0-py3.4.egg/distributed/utils.py in sync(loop, func, *args, **kwargs)
     82 
     83     a = loop.add_callback(f)
---> 84     e.wait()
     85     return result[0]
     86 

/home/ec2-user/anaconda3/lib/python3.4/threading.py in wait(self, timeout)
    551             signaled = self._flag
    552             if not signaled:
--> 553                 signaled = self._cond.wait(timeout)
    554             return signaled
    555         finally:

/home/ec2-user/anaconda3/lib/python3.4/threading.py in wait(self, timeout)
    288         try:    # restore state no matter what (e.g., KeyboardInterrupt)
    289             if timeout is None:
--> 290                 waiter.acquire()
    291                 gotit = True
    292             else:

KeyboardInterrupt: 
```
Do you think this is at all related to the hanging tornado co-routines I am experiencing when I run the tests?  This is running on my Ubuntu linux machine, distributed master branch, Anaconda python 3.5 and Tornado 4.3.  Let me know what you think!

**Comment by mrocklin** [comment]
I've been improving error logging a bit this morning.  Let me try to push something out later today and hopefully we can get more visibility into the exception.

**Comment by broxtronix** [comment]
Sounds great.  Thank you!

**Comment by mrocklin** [comment]
As of https://github.com/blaze/distributed/pull/49 `sync` should now cleanly raise and log errors

**Comment by mrocklin** [comment]
This seems to be done.  Closing.
