### ISSUE TITLE
Shut down cluster from user commands

### ISSUE THREAD

**Issue by mrocklin** [blaze/distributed#29]
All of the Center/Worker/Nanny support termination commands, we just need to build a small function to trigger these and verify clean shutdown.

There is no particular reason why this needs to be attached to the executor.  It could be a freestanding function.  Perhaps we should put it on the Executor anyway though just for convenience.

**Comment by mrocklin** [comment]
@broxtronix is this still desired?

**Comment by broxtronix** [comment]
I have been pretty happy starting and stopping my cluster from the command line using the `dcluster` command. I don't think this functionality is needed at the moment, at least not in my use case!
