### ISSUE TITLE
Dask dataframe does not count last data chunk

### ISSUE THREAD

**Issue by martindurant** [blaze/distributed#51]
The following code demonstrates:

```python
import distributed
ex = distributed.Executor('localhost:8787')
import numpy
data_list = [numpy.random.rand(1000) for _ in range(1000)]
out = ex.scatter(data_list)
import dask.dataframe as dd
import dask
dask.set_options(get=ex.get)
import pandas as pd
dfs = ex.map(lambda x: pd.DataFrame({'x': x}), out)
dsk = {('mydf', i): df for i, df in enumerate(dfs)}
data = dd.DataFrame(dsk, 'mydf', ['x'], [None]*len(dfs))
print(len(data))  # should be 1000000
```

and I have seen similar behaviour in more typical datasets: it's specifically the data belonging to the last future, `dfs[-1]` which isn't counted. Contrast with the following, which gives the correct value:
`ex.submit(sum, ex.map(len, dfs))`

**Comment by mrocklin** [comment]
Divisions should be `[None] * (len(dfs) + 1)`

It is defined as the minimum value of the index of each partition, plus the maximum value of the last partition (hence the +1) or `None` in all values.

**Comment by martindurant** [comment]
Sorted, thank you.
