### ISSUE TITLE
dworker should wait for dcenter to come up

### ISSUE THREAD

**Issue by hussainsultan** [blaze/distributed#61]
if dworker is running before dcenter process has started, worker never connects to the center. Consider:

```
$dworker 10.52.10.8:8787
distributed.nanny - INFO - Nanny starts worker process 10.52.10.8:8788
distributed.worker - INFO - Start worker at             10.52.10.8:8789
distributed.worker - INFO - Waiting to connect to       10.52.10.8:8787
```
and then:

```
$ dcenter 
distributed.dcenter - INFO - Start center at 10.52.10.8:8787
```

it appears that while dcenter process is running after dworker, dworker does not try to connect with the center again.

This is a slight issue when lunching a mesos task with center and worker process; mesos launches all tasks (center and workers) simultaneously, however the cadence of when center and worker task start running may not be in-sync.

**Comment by mrocklin** [comment]
Hrm, this is odd.  I actually get correct behavior here

```
mrocklin@notebook:~$ dworker 127.0.0.1:8787
distributed.nanny - INFO - Start Nanny at:             192.168.1.106:36639
distributed.worker - INFO - Start worker at             192.168.1.106:39815
distributed.worker - INFO - Waiting to connect to       127.0.0.1:8787
```
```
mrocklin@notebook:~$ dcenter 
distributed.dcenter - INFO - Start center at 192.168.1.106:8787
distributed.core - INFO - Connection from 127.0.0.1:51274 to Center
distributed.center - INFO - Register ('192.168.1.106', 39815)
```

By default The worker retries every 500 ms until connection with no timeout

https://github.com/blaze/distributed/blob/master/distributed/worker.py#L106-L114

```python
        while True:
            try:
                resp = yield self.center.register(
                        ncores=self.ncores, address=(self.ip, self.port),
                        nanny_port=self.nanny_port, keys=list(self.data))
                break
            except OSError:
                logger.debug("Unable to register with center.  Waiting")
                yield gen.sleep(0.5)
```

Perhaps the exception type is different for different OS's?  I'm on linux.
